### ISSUE TITLE
portfolio piece's pictures

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/mBluebear.github.io#1]
_ There is a big gap between the picture of Tiffany piece and the description of the project. Since the heights of each pictures are different. The project description is placed at the bottom of the tallest picture.
_ For some pieces, when it was clicked, the picture won't appear until the dot under the carousel is clicked.
_ For some pieces, the first picture isn't aligned in the middle, it's aligned to the left edge. Then after the next dot under the carousel is clicked, all the pictures are aligned nicely in the middle

**Comment by thomasjbradley** [comment]
I'm not sure I see these problems. Did you fix them already?

**Comment by mBluebear** [comment]
Yes, Thomas, I just fixed them today :)

**Comment by thomasjbradley** [comment]
Awesome. Please close this issues since it's now fixed.
